# 차량 판매 정보 시스템
# 필요 테이블 목록
# CAR_INFO (자동차 정보) - MODEL_NO(PK), MODEL_NAME, PRICE, MANUFACTURER
# SALES_INFO (자동차판매정보) - SALE_NO, BUYER_NAME, BUYER_PHONE, COLOR, SALE_DATE, MODEL_NO 

CREATE TABLE CAR_INFO (
	MODEL_NO INT PRIMARY KEY AUTO_INCREMENT,
	MODLE_NAME VARCHAR(100) NOT NULL,
	PRICE INT NOT NULL,
	MANUFACTURER VARCHAR(50) NOT NULL
);

CREATE TABLE SAELS_INFO (
	SALE_NO INT PRIMARY KEY AUTO_INCREMENT,
	BUYER_NAME VARCHAR(100) NOT NULL,
	BUYER_PHONE VARCHAR(20),
	COLOR VARCHAR(20) NOT NULL,
	SALE_DATE DATETIME NOT NULL,
	MODEL_NO INT NOT NULL REFERENCES CAR_INFO(MODEL_NO)
);